source  'https://github.com/UniPassID/UniPass-Swift-SDK-Spec.git'

project 'UniPassWalletDemo.xcodeproj'

platform :ios, '12.0'

# ignore import pod lib warnings
inhibit_all_warnings!
target 'UniPassWalletDemo' do 
#   pod 'UniPassSDK', '0.0.4'  # for pod release verfication
    pod 'UniPassSDK', :path => '../' # for local debug
end
