# 下面两行是指明依赖库的来源地址
source  'https://github.com/UniPassID/UniPass-Swift-SDK.git'

project 'UniPassWalletDemo.xcodeproj'

# 说明平台是ios，版本是9.0
platform :ios, '12.0'

# 忽略引入库的所有警告（强迫症者的福音啊）
inhibit_all_warnings!
target 'UniPassWalletDemo' do 
 # pod 'UniPassSDK', '0.0.5'  #验证发版版本用这个
  pod 'UniPassSDK', :path => '../' #本地调试用这个
end
